import type { Metadata } from 'next'
import { ReactNode } from 'react'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function AuthLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	return <>{children}</>
}
