import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.scss'
import { ReactNode } from 'react'
import { Providers } from '../providers/Providers'
import { Header } from '../shared/Header'
// import { Footer } from '../shared/Footer'
const montserrat = Montserrat({
	subsets: ['latin'],
	weight: ['400', '500', '700', '900'],
	preload: true,
})

export const metadata: Metadata = {
	title: 'Create Next App',

	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${montserrat.className} font-normal text-base`}>
				<Providers>
					<Header />
					{children}
					{/* <Footer /> */}
				</Providers>
			</body>
		</html>
	)
}
